# Generated by Django 4.1.4 on 2023-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.IntegerField()),
                ('Sname', models.CharField(max_length=100)),
                ('Sage', models.IntegerField()),
                ('Saddress', models.TextField()),
                ('Scontact', models.IntegerField()),
            ],
        ),
    ]
